// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"go-chi-wire/internal/handler"
	"go-chi-wire/internal/router"
	"go-chi-wire/internal/service"
	"net/http"
)

// Injectors from wire.go:

func InitializeRouter() http.Handler {
	userService := service.NewUserService()
	userHandler := handler.NewUserHandler(userService)
	httpHandler := router.NewUserRouter(userHandler)
	return httpHandler
}
